### PR TITLE
1.0.0-alpha.1

### PR DESCRIPTION
**Pull request by ewilan-riviere**
This version rework completely the library, it's not compatible with previous version. Now you can use OPDS 2.0 with partial support.

### `Opds::class`

-   static method `response()` removed, now static method is `Opds::make()` and `get()` is a arrow method:

```php
$opds = Opds::make();

$debug = $opds->get(); // `Opds::class` instance with response

return $opds->response(); // `never` because send response
```

-   To add `entries`, you have to use `feeds()` arrow method
    -   `feeds()` accept `OpdsEntryBook[]` or `OpdsEntryNavigation[]` but also `OpdsEntryNavigation` or `OpdsEntryBook`
-   To add `isSearch`, you have to use `isSearch()` arrow method
-   To add `title`, you have to use `title()` arrow method
-   To add `url`, you have to use `url()` arrow method (only for testing, URL is automatically generated)
-   OPDS version can be handle by query param `version`: `?version=2.0` or `?version=1.2`
-   To get generate response and keep `Opds::class` instance, you can use `get()` arrow method
-   To get response as XML or JSON, you can use `response()` arrow method
-   `asString` param removed, now you can use `get()` arrow method to debug response
-   To get response after `get()` you can use `getResponse()` arrow method (different that `response()` will return full content as `never` with headers)

```php
use Kiwilan\Opds\Opds;
use Kiwilan\Opds\OpdsVersionEnum;

$entries = [];

$opds = Opds::make(new OpdsConfig()) // Accept `OpdsConfig::class`
  ->title('My search') // To set feed title
  ->isSearch() // To set feed as search
  ->url('https://example.com/search') // Only for testing, URL is automatically generated
  ->feeds($entries); // Accept `OpdsEntryBook[]`, `OpdsEntryNavigation[]`, `OpdsEntryNavigation` or `OpdsEntryBook`

return $opds->get();
```

### Misc

-   `OpdsConfig`
    -   `usePagination` is now default to `false`
    -   `forceJson` param allow to skip OPDS 1.2
-   `OpdsEntry` is now `OpdsEntryNavigation`
-   `OpdsEngine` rewrite completely
-   `OpdsResponse` can be debug with `getContent()` method to inspect response (accessible if you use `get()` method)
-   `OpdsEntry` items have now `get` prefix for all getter

## Added

-   add ODPS 2.0 support partially

### CODE REVIEW

**Comment by ewilan-riviere** [comment]
@mikespub Do you want to beta-test `1.0.0` with partial JSON support?

**Comment by mikespub** [comment]
I can give it a go in my [kiwilan](https://github.com/mikespub-org/seblucas-cops/tree/kiwilan) branch but what do you mean by "partial support"? If it doesn't generate a complete OPDS 2.0 feed yet, then I'm afraid it won't be very helpful at this point...

With the pre-1.0 version I simply rewrote the OPDS renderer to make use of Kiwilan\Opds to render the XML output based on the entries passed by $page: [lib/Output/KiwilanOPDS.php](https://github.com/mikespub-org/seblucas-cops/blob/kiwilan/lib/Output/KiwilanOPDS.php)

And the new entrypoint [opds.php](https://github.com/mikespub-org/seblucas-cops/blob/kiwilan/opds.php) was a straight copy of the existing [feed.php](https://github.com/mikespub-org/seblucas-cops/blob/kiwilan/feed.php), calling $OPDSRender->render($page, $request) and echo-ing the response.

That worked out nicely to generate the same OPDS 1.2 output as the existing renderer, so I was hoping I could use a similar approach when switching to OPDS 2.0 output:
use a library that already generates OPDS 2.0-compliant output for different collections and feeds as defined in the specs, and then see how best to map/adapt the COPS page structure to generate meaningful COPS feeds.

Right now 1.0.0-alpha.1 still seems to be missing some of the building blocks, or maybe I missed something?

One last point for future versions: for a re-usable package, it would be easier if we could get back the output as a result so we can handle the response ourselves afterwards, rather than let OPDSResponse->get() handle it.

Thanks

**Comment by ewilan-riviere** [comment]
This version don't support [facets](https://drafts.opds.io/opds-2.0#14-facets), [groups](https://drafts.opds.io/opds-2.0#15-groups) and [pagination](https://drafts.opds.io/opds-2.0#3-pagination).

Pagination will be first feature planned. For [metadata](https://drafts.opds.io/opds-2.0#42-metadata), this version partially support with just basics entries, for metadata into belongsTo entry, just series supported for now.

> One last point for future versions: for a re-usable package, it would be easier if we could get back the output as a result so we can handle the response ourselves afterwards, rather than let OPDSResponse->get() handle it.

I update `Opds::class`, now you can use `get()` method to get full instance with generated response into `getResponse()`. Method `response()` is available to send response to browser.

If you want to test OPDS 2.0 only when is full ready, I will send you a notification when all is done.

**Comment by mikespub** [comment]
Thanks Ewilan, I would indeed prefer to wait for a more complete version before testing - sorry about that.

I've spent quite some time dragging the COPS code base from PHP 5.x to PHP 8.x, and adding OPDS 2.0 would be nice to have, so after dealing with a bunch of resource packages that hadn't been updated in 8 years, I was excited to find a modern package I could re-use that might provide that in the future :-)

**Pull request merged**
